### ISSUE TITLE
How can I get speed of the car from the data

### ISSUE THREAD

**Issue by sardanian** [Tinker-Twins/AutoDRIVE#12]
Is there an easy way to get odometry data? More specifically to get linear velocity? I see there is linear acceleration, but not velocity. I am not familiar on how to calculate the linear velocity and before figuring out the calculations was wondering if it was already done or available in some other form.

This question is in reference to the Toolkit.

**Comment by Tinker-Twins** [comment]
In a newer build, we now expose `speed` of the vehicle (and some more useful information) via the API. Please check out [this](https://github.com/AutoDRIVE-Ecosystem/AutoDRIVE-F1TENTH-Sim-Racing/releases/tag/2024-iros-practice) release.
