### ISSUE TITLE
WSL2 Is not working

### ISSUE THREAD

**Issue by JuanCarlos-TiqueRangel** [Tinker-Twins/AutoDRIVE#14]
Hello Everyone, 

I know the current simulations are working just in a Linux based environment. However, is it possible to use WSL2 ubuntu 22.04 to run the simulation ? I was trying to run as it was in Native Ubuntu But I always got the same error:

```
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Segmentation fault (core dumped)
```

Or there is another option to use the ros2 stack in windows ? Thank you in advance.

**Comment by Tinker-Twins** [comment]
Apart from running the containerized version (which may have issues accessing the GPU if not set up correctly), you can always run the simulator locally (it's much easier to access the GPU this way) on Windows, Linux or macOS. The devkit can be run either locally (if you have the environment and dependencies set up, e.g. Linux with ROS/ROS 2) or as a container (on any platform). Either of the combinations has been tested to interface the simulator with the devkit correctly.

Specifically for installing/running ROS 2 on Windows OS, you can check out the official [ROS 2 Humble Windows Installation Documentation](https://docs.ros.org/en/humble/Installation/Windows-Install-Binary.html) and try building the devkit from the source.

Hope this helps!
