### ISSUE TITLE
Is it possible to make the simulator window resizable? 

### ISSUE THREAD

**Issue by cookiegg** [Tinker-Twins/AutoDRIVE#9]
I used `./'AutoDRIVE Simulator.x86_64' -screen-fullscreen 0` to start the simulator in the ubuntu(20.04) system, but found that the window could not be zoomed except when minimized.

**Comment by Tinker-Twins** [comment]
Yes, you can export the simulator standalone executables with custom screen resolution and window size. The following screenshot shows the export settings.

![image](https://github.com/Tinker-Twins/AutoDRIVE/assets/40835293/28579180-8fc9-4a2f-aa9c-12b389b85d64)

Additionally, we have updated [AutoDRIVE Simulator 0.3.0](https://github.com/Tinker-Twins/AutoDRIVE/releases/tag/Simulator-0.3.0) release to include the standalone executables with a resizable window:
- [Windows](https://github.com/Tinker-Twins/AutoDRIVE/releases/download/Simulator-0.3.0/AutoDRIVE_Simulator_Resizable_Windows.zip)
- [Linux](https://github.com/Tinker-Twins/AutoDRIVE/releases/download/Simulator-0.3.0/AutoDRIVE_Simulator_Resizable_Linux.zip)
- [macOS](https://github.com/Tinker-Twins/AutoDRIVE/releases/download/Simulator-0.3.0/AutoDRIVE_Simulator_Resizable_macOS.zip)
